### ISSUE TITLE
Problems with "eDreymaR"

### ISSUE THREAD

**Issue by DreymaR** [nhermosilla14/latam-colmak#2]
Hi! This is DreymaR from the Colemak community.

These variants are derived from my work, and they are presented with a misspelling of my name. Please correct "eDreymaR" to "DreymaR". But thanks for mentioning me!

However, I refuse to have my name associated with the "Colemak for gaming" layout variant, as I think it is a very bad idea that I do not want my name on. Please remove any reference to me in that variant. Better still, just delete it if you have started to realize how bad it is – I think it may have been a beginner's mistake? Hehe. See this:

https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/issues/327

**Comment by nhermosilla14** [comment]
Hi! To be honest, I just made this in order to be able to use them myself (which I no longer do). I did not really think it would ever be merged anywhere (and of course I see now it wasn't even made in the proper way). It's been many years already, as you can probable tell from the last commit.
I will correct the spelling and make clear you are not in any way responsible for the "gaming" variation, I'm sorry for not doing it right in the first place.

**Comment by DreymaR** [comment]
Thanks! 😺
